#pragma once
#include "inttypes.hpp"
namespace th095 {
#if !defined(TH095_MATCH_EXACT) && !defined(DIFFBUILD)
enum PhotoPlayerMode
{
    PHOTO_PLAYER_MODE_ENTERING = 0,
    PHOTO_PLAYER_MODE_ACTIVE = 1,
    PHOTO_PLAYER_MODE_DEATH_TRANSITION = 2,
    PHOTO_PLAYER_MODE_PHOTO_LIMIT_TRANSITION = 3,
};

enum PhotoPlayerMovementDirection
{
    PHOTO_PLAYER_DIRECTION_NONE = 0,
    PHOTO_PLAYER_DIRECTION_UP = 1,
    PHOTO_PLAYER_DIRECTION_DOWN = 2,
    PHOTO_PLAYER_DIRECTION_LEFT = 3,
    PHOTO_PLAYER_DIRECTION_RIGHT = 4,
    PHOTO_PLAYER_DIRECTION_UP_LEFT = 5,
    PHOTO_PLAYER_DIRECTION_UP_RIGHT = 6,
    PHOTO_PLAYER_DIRECTION_DOWN_LEFT = 7,
    PHOTO_PLAYER_DIRECTION_DOWN_RIGHT = 8,
};

#ifndef TH095_IOS_PORTABLE_LAYOUT
#ifndef TH095_IOS_PORTABLE_LAYOUT
typedef char PhotoPlayerMovementDirectionSizeIs4[
    (sizeof(PhotoPlayerMovementDirection) == 4) ? 1 : -1];
#endif
#endif

enum PhotoPlayerCameraTrackingMode
{
    PHOTO_PLAYER_CAMERA_TRACKING_FREE = 0,
    PHOTO_PLAYER_CAMERA_TRACKING_TARGET = 1,
    PHOTO_PLAYER_CAMERA_TRACKING_TARGET_SLOW = 2,
};

#ifndef TH095_IOS_PORTABLE_LAYOUT
#ifndef TH095_IOS_PORTABLE_LAYOUT
typedef char PhotoPlayerCameraTrackingModeSizeIs4[
    (sizeof(PhotoPlayerCameraTrackingMode) == 4) ? 1 : -1];
#endif
#endif
#endif

#if defined(TH095_MATCH_EXACT) || defined(DIFFBUILD)
#define TH095_PHOTO_PLAYER_CAMERA_TRACKING_FREE 0
#define TH095_PHOTO_PLAYER_CAMERA_TRACKING_TARGET 1
#define TH095_PHOTO_PLAYER_CAMERA_TRACKING_TARGET_SLOW 2
#else
#define TH095_PHOTO_PLAYER_CAMERA_TRACKING_FREE PHOTO_PLAYER_CAMERA_TRACKING_FREE
#define TH095_PHOTO_PLAYER_CAMERA_TRACKING_TARGET PHOTO_PLAYER_CAMERA_TRACKING_TARGET
#define TH095_PHOTO_PLAYER_CAMERA_TRACKING_TARGET_SLOW PHOTO_PLAYER_CAMERA_TRACKING_TARGET_SLOW
#endif


}
