#pragma once

namespace th095
{

enum SupervisorViewportSlot
{
    SUPERVISOR_VIEWPORT_PLAYFIELD = 0,
    SUPERVISOR_VIEWPORT_FULL_WINDOW = 1,
    SUPERVISOR_VIEWPORT_SLOT_COUNT = 2,
};

} // namespace th095

#define TH095_SUPERVISOR_VIEWPORT_PLAYFIELD th095::SUPERVISOR_VIEWPORT_PLAYFIELD
#define TH095_SUPERVISOR_VIEWPORT_FULL_WINDOW th095::SUPERVISOR_VIEWPORT_FULL_WINDOW
#define TH095_SUPERVISOR_VIEWPORT_SLOT_COUNT th095::SUPERVISOR_VIEWPORT_SLOT_COUNT
